name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'oldrel-1'}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install TinyTeX
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            choco install tinytex
            refreshenv
            Write-Output "C:\tools\TinyTeX\bin\win32" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH
          else
            wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
            echo "$HOME/.TinyTeX/bin/x86_64-linux" >> $GITHUB_PATH
          fi

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: warning
          build_args: --no-manual

      - name: Upload check results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
          path: ./*.Rcheck/**
